apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trident

resources: 
  - trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - podsecuritypolicy_unprivileged.yaml
  - operator.yaml
  - tridentorchestrator_cr.yaml
#?  - sealed-secret-trident-backend.yaml
  - backend-tbc-ontap-san.yaml