apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-rbac
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/rbac/base
    repoURL: https://github.com/shah-zobair/gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
