apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/sealed-secrets-operator-helm.sealed-secrets: ''
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: sealed-secrets-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sealed-secrets-operator-helm.v0.0.2