apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - sAMAccountName
        name:
        - displayName
        preferredUsername:
        - sAMAccountName
      bindDN: CN=Ocp Ldap,OU=Generic Accounts,DC=vodafone,DC=local
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldaps://ldaps.vodafone.local:636/OU=VFTRAddressList,DC=vodafone,DC=local?samAccountName,OU=OpenShift,OU=No Desktop Control,DC=vodafone,DC=local)
    mappingMethod: claim
    name: Vodafone-ldaps
    type: LDAP
