apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    retentionPolicy: 
      application:
        maxAge: 7d
      infra:
        maxAge: 3d
      audit:
        maxAge: 3d
    elasticsearch:
      nodeCount: 3 
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      storage:
        storageClassName: "thick" 
        size: 300G
      resources: 
        requests:
          memory: "12Gi"
          cpu: "2"
      proxy: 
        resources:
          limits:
            memory: 512Mi
          requests:
             memory: 512Mi
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"  
    kibana:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      replicas: 1
  curation:
    type: "curator"
    curator:
      schedule: "30 3 * * *" 
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}

